In [30]:
l = [1,[2,[3,4],5],6,7,[8],9,10,[11,12,[13,14],15],16,[17,18,[[19,20,21,22,23],24],[25,26],27],28]
#Dostań się do podanej lub podanych wartości przez indeksowanie
# 5
# 4
# 10
# [[2, [3, 4], 5], 6, 7, [8]]
# [11, [13, 14]]
# 24
# 8
# [23, 22, 21, 20, 19]

In [37]:
l[1][2]

5

In [36]:
l[1][1][1]

4

In [38]:
l[6]

10

In [39]:
l[1:5]

[[2, [3, 4], 5], 6, 7, [8]]

In [40]:
l[7][0], l[7][2]

(11, [13, 14])

In [41]:
l[-2][-3][1]

24

In [42]:
l[4]

[8]

In [43]:
x = l[-2][-3][0]
posortowane = sorted(x, reverse = True)
print(posortowane)

[23, 22, 21, 20, 19]


In [44]:
import os

In [45]:
os.getcwd()

'/Users/piotr/Documents/Koło'

In [47]:
kazio = os.path.join(os.getcwd(), 'Tygrysek_Kazimierz')

In [48]:
print(kazio)

/Users/piotr/Documents/Koło/Tygrysek_Kazimierz


In [62]:
kazio2=kazio.split('/')

In [63]:
kazio2

['', 'Users', 'piotr', 'Documents', 'Koło', 'Tygrysek_Kazimierz']

In [64]:
kazio2[2]

'piotr'

In [65]:
import numpy as np

In [98]:
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [129]:
ar = np.append(ar, [4,5,9,10,23,-14,55,13])

In [115]:
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [128]:
ar[-6]

9

In [124]:
ar[ar<0]

array([ -3, -10, -98, -14])

In [125]:
np.mean(ar)

12.1

In [126]:
ar_abs = np.reciprocal(ar)

In [130]:
ar_abs

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])